CREATE DATABASE chaussures_db;


CREATE TABLE CHAUSSURE (
    ID SERIAL PRIMARY KEY,
    MARQUE VARCHAR(30) NOT NULL,
    COULEUR VARCHAR(30),
    PRIX NUMERIC(10, 2)
);

ALTER TABLE CHAUSSURE ADD COLUMN TAILLE DECIMAL(4,1);
